print("Birinci satır:","Hello World")
print('Hello World')
print('Kayra\'nın Eşşeği')
print("""Merhaba
Dünya""")
print("Ahmet\tKral")
print("Ahmet\nKral")
ebcik="Merhaba"
ebcik2="Dünya"
print(ebcik)
print(ebcik+" "+ebcik2)
print(ebcik[0])
print(ebcik[-2])
print(ebcik[3:5])
print(ebcik[::3])
print(ebcik[::-1])
print(ebcik.upper())
ebcik=ebcik.upper()
print(ebcik)
ebcik=ebcik.lower()
print(ebcik)
ebcik=ebcik.capitalize()
print(ebcik)
print(ebcik.startswith("Me"))
print(ebcik.endswith("Ba"))
print(len(ebcik))
print("HAİN"*5)
print("{}, {}".format(ebcik,ebcik2))
print(f"{ebcik}, {ebcik2}")
